### ISSUE TITLE
Add new page for Arbor Lodge Park

### ISSUE THREAD

**Issue by kmic** [ArborLodgePDX/arbor-lodge-neighborhood-website#13]
As we're getting ready to launch more regular park cleanups, we'd like to add a page to the site to include details and be able to direct people to the site.  arborlodgepdx.org/park

**Comment by dustatron** [comment]
so it looks like you can simply make a new page in Contentful and set the route under Page URL.
I just made a page called Park in contentful 
https://arborlodgepdx.org/park

Here is he contentful page
https://app.contentful.com/spaces/sphy73k6uzpa/entries/47bL0ULPsoS7HkKnB0Epwz

**Comment by kmic** [comment]
Awesome, thanks Dusty!
