### ISSUE TITLE
Add calendar page

### ISSUE THREAD

**Issue by kmic** [ArborLodgePDX/arbor-lodge-neighborhood-website#6]
I'm behind on putting together my wish list of updates for our site, but the important one I'd love to do when you have time is add a Calendar page (arborlodgepdx.org/calendar) -- it can go under the Resources menu. It'll probably work best if we do this page without the right sidebar.

---

<iframe src="https://calendar.google.com/calendar/embed?height=600&wkst=1&bgcolor=%23ffffff&ctz=America%2FLos_Angeles&src=cHVibGljQGFyYm9ybG9kZ2VuZWlnaGJvcmhvb2QuY29t&color=%23039BE5" style="border:solid 1px #777" width="800" height="600" frameborder="0" scrolling="no"></iframe>

**Comment by dustatron** [comment]
Added new calendar page

**Comment by kmic** [comment]
Dusty-

Saw you added the calendar page. Thank you!

Quick question. I’ve only seen it in mobile, do you think it’d look better if we change the embed code to be the agenda (list) view?

On mobile I don’t see the full names. I didn’t think of it when I asked.

Let me know. 

Thanks!
