### ISSUE TITLE
Most pages have generic HTML title

### ISSUE THREAD

**Issue by kmic** [ArborLodgePDX/arbor-lodge-neighborhood-website#7]
Most pages on the site have a title of "Arbor Lodge Neighborhood, Portland OR" instead of the title coming from Contentful. The only pages that do not have this problem are the pages under Resources ([Graffiti / Garbage Cleanup](https://arborlodgepdx.org/cleanup), [Disaster Preparedness](https://arborlodgepdx.org/disaster-preparedness) )

**Comment by ArborLodgePDX** [comment]
Updated page to use the title from contentful for the page title in the tab.
